import { GoogFonts } from "./ui/fonts";
import "./globals.css";
import Header from "./Header";
import Footer from "./Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${GoogFonts.Poppins.variable} ${GoogFonts.PlayFairDisplay.variable} antialiased poppins`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
